// ─── Demo Tracks ─────────────────────────────────────────────────────────────
// All tracks are clearly flagged isDemo:true and labelled in the UI
// Audio: royalty-free samples from SoundHelix (CC0)

export const DEMO_TRACKS = [
  {
    id: 'demo-1',
    title: 'Midnight Vibes',
    artist: 'Luna Beats',
    genre: 'Lo-fi Hip Hop',
    isDemo: true,
    postcard: require('../../assets/postcards/postcard_midnight.jpg'),
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    duration: 375,
    likeCount: 1247,
    commentCount: 89,
    shareCount: 234,
    liked: false,
    lyrics: [
      { time: 0, text: '♪ Instrumental intro ♪' },
      { time: 8, text: 'Walking through the city at midnight' },
      { time: 14, text: 'Neon lights reflecting off the pavement' },
      { time: 20, text: 'Lost in the rhythm of the night' },
      { time: 26, text: 'Every beat echoes through the streets' },
      { time: 32, text: 'Headphones on, world fades away' },
      { time: 38, text: 'The bass drops, my heart starts to sway' },
      { time: 44, text: 'Midnight vibes, can\'t get enough' },
      { time: 50, text: 'This lo-fi groove is calling my bluff' },
      { time: 58, text: 'Streetlights humming overhead' },
      { time: 64, text: 'Thoughts tangled up inside my head' },
      { time: 70, text: 'But the melody keeps pulling me through' },
      { time: 76, text: 'Every note feels like something new' },
    ],
  },
  {
    id: 'demo-2',
    title: 'Golden Hour',
    artist: 'Desi Cipher',
    genre: 'Desi Hip Hop',
    isDemo: true,
    postcard: require('../../assets/postcards/postcard_golden.jpg'),
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    duration: 298,
    likeCount: 2891,
    commentCount: 214,
    shareCount: 567,
    liked: false,
    lyrics: [
      { time: 0, text: '♪ Beat drops ♪' },
      { time: 6, text: 'Sun setting over concrete towers' },
      { time: 12, text: 'Golden light painting every corner' },
      { time: 18, text: 'We came from nothing, built these powers' },
      { time: 24, text: 'Every bar written on that border' },
      { time: 30, text: 'Streets raised me, gave me this sound' },
      { time: 36, text: 'Underground flow, now look around' },
      { time: 42, text: 'Golden hour, the city shines bright' },
      { time: 48, text: 'From the shadows stepping into light' },
      { time: 56, text: 'Pen to paper, fire to the page' },
      { time: 62, text: 'Every verse, breaking out the cage' },
    ],
  },
  {
    id: 'demo-3',
    title: 'Neon Dreams',
    artist: 'Cloud Walker',
    genre: 'Chill Trap',
    isDemo: true,
    postcard: require('../../assets/postcards/postcard_neon.jpg'),
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    duration: 412,
    likeCount: 956,
    commentCount: 67,
    shareCount: 145,
    liked: false,
    lyrics: [
      { time: 0, text: '♪ Atmospheric pad ♪' },
      { time: 10, text: 'Raindrops on the window, neon glow' },
      { time: 18, text: 'Inside this room the world moves slow' },
      { time: 26, text: 'Purple haze through the curtain seams' },
      { time: 34, text: 'Caught between reality and dreams' },
      { time: 42, text: 'Let the beat carry me away' },
      { time: 50, text: 'Tomorrow\'s worries can wait another day' },
      { time: 58, text: 'Neon dreams, floating through the night' },
      { time: 66, text: 'Everything\'s gonna be alright' },
    ],
  },
  {
    id: 'demo-4',
    title: 'Street Lights',
    artist: 'Raw Theory',
    genre: 'Boom Bap',
    isDemo: true,
    postcard: require('../../assets/postcards/postcard_street.jpg'),
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    duration: 267,
    likeCount: 3421,
    commentCount: 312,
    shareCount: 789,
    liked: false,
    lyrics: [
      { time: 0, text: '♪ Boom bap intro ♪' },
      { time: 6, text: 'Under street lights, shadows dance' },
      { time: 12, text: 'Every corner tells a story of chance' },
      { time: 18, text: 'Concrete jungle, we made it our stage' },
      { time: 24, text: 'Every wall is another page' },
      { time: 30, text: 'Raw and uncut, that\'s the vibe' },
      { time: 36, text: 'Real recognize real, we survive' },
      { time: 42, text: 'Street lights guiding every step' },
      { time: 48, text: 'In this game, we never slept' },
      { time: 54, text: 'Brick by brick, bar by bar' },
      { time: 60, text: 'Look how far we\'ve come, who we are' },
    ],
  },
  {
    id: 'demo-5',
    title: 'City Pulse',
    artist: 'Neon Collective',
    genre: 'Electronic Hip Hop',
    isDemo: true,
    postcard: require('../../assets/postcards/postcard_pulse.jpg'),
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    duration: 344,
    likeCount: 1789,
    commentCount: 156,
    shareCount: 412,
    liked: false,
    lyrics: [
      { time: 0, text: '♪ Synth wave ♪' },
      { time: 8, text: 'Feel the pulse of the city tonight' },
      { time: 14, text: 'Electric veins running through the night' },
      { time: 20, text: 'Frequencies clash, colors collide' },
      { time: 26, text: 'In the current, we ride' },
      { time: 32, text: 'Bass in my chest, light in my eyes' },
      { time: 38, text: 'Digital horizons, analog skies' },
      { time: 44, text: 'City pulse, never stops beating' },
      { time: 50, text: 'Every rhythm, a reason for breathing' },
      { time: 58, text: 'Voltage rising through the floor' },
      { time: 64, text: 'Open the door, there\'s always more' },
    ],
  },
];

export const formatDuration = (seconds) => {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins}:${secs.toString().padStart(2, '0')}`;
};

export const formatCount = (count) => {
  if (count >= 1000) {
    return `${(count / 1000).toFixed(1)}K`;
  }
  return count.toString();
};
